var SEGMENT_ORIENTATION = { UP: 0, DOWN: 1, LEFT: 2, RIGHT: 3 };
var POINT_TYPE          = { CORNER: 0, GROOVE: 1 };
var POINT_ORIENTATION   = { NW: 0, SW: 1, SE: 2, NE: 3 };

var CAST_PER_CORNER_ORIENTATION = {};

var CAST_PARAM_NE = { s1: SEGMENT_ORIENTATION.DOWN, s2: SEGMENT_ORIENTATION.LEFT,  x:  1, y: -1, listId: POINT_ORIENTATION.NE };
var CAST_PARAM_NW = { s1: SEGMENT_ORIENTATION.DOWN, s2: SEGMENT_ORIENTATION.RIGHT, x: -1, y: -1, listId: POINT_ORIENTATION.NW };
var CAST_PARAM_SE = { s1: SEGMENT_ORIENTATION.UP,   s2: SEGMENT_ORIENTATION.LEFT,  x:  1, y:  1, listId: POINT_ORIENTATION.SE };
var CAST_PARAM_SW = { s1: SEGMENT_ORIENTATION.UP,   s2: SEGMENT_ORIENTATION.RIGHT, x: -1, y:  1, listId: POINT_ORIENTATION.SW };

CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.NW] = [CAST_PARAM_NE, CAST_PARAM_SW];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.NE] = [CAST_PARAM_NW, CAST_PARAM_SE];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.SW] = [CAST_PARAM_NW, CAST_PARAM_SE];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.SE] = [CAST_PARAM_NE, CAST_PARAM_SW];

//▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
exports.SEGMENT_ORIENTATION         = SEGMENT_ORIENTATION;
exports.POINT_TYPE                  = POINT_TYPE;
exports.POINT_ORIENTATION           = POINT_ORIENTATION;
exports.CAST_PER_CORNER_ORIENTATION = CAST_PER_CORNER_ORIENTATION;
