var SEGMENT_ORIENTATION = { UP: 0, DOWN: 1, LEFT: 2, RIGHT: 3 };
var POINT_TYPE          = { CORNER: 0, GROOVE: 1 };
var POINT_ORIENTATION   = { NO: 0, SO: 1, SE: 2, NE: 3 };

var CAST_PER_CORNER_ORIENTATION = {};

var CAST_PARAM_NE = { s1: SEGMENT_ORIENTATION.DOWN, s2: SEGMENT_ORIENTATION.LEFT,  x:  1, y: -1, listId: POINT_ORIENTATION.NE };
var CAST_PARAM_NO = { s1: SEGMENT_ORIENTATION.DOWN, s2: SEGMENT_ORIENTATION.RIGHT, x: -1, y: -1, listId: POINT_ORIENTATION.NO };
var CAST_PARAM_SE = { s1: SEGMENT_ORIENTATION.UP,   s2: SEGMENT_ORIENTATION.LEFT,  x:  1, y:  1, listId: POINT_ORIENTATION.SE };
var CAST_PARAM_SO = { s1: SEGMENT_ORIENTATION.UP,   s2: SEGMENT_ORIENTATION.RIGHT, x: -1, y:  1, listId: POINT_ORIENTATION.SO };

CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.NO] = [CAST_PARAM_NE, CAST_PARAM_SO];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.NE] = [CAST_PARAM_NO, CAST_PARAM_SE];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.SO] = [CAST_PARAM_NO, CAST_PARAM_SE];
CAST_PER_CORNER_ORIENTATION[POINT_ORIENTATION.SE] = [CAST_PARAM_NE, CAST_PARAM_SO];

//▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
exports.SEGMENT_ORIENTATION         = SEGMENT_ORIENTATION;
exports.POINT_TYPE                  = POINT_TYPE;
exports.POINT_ORIENTATION           = POINT_ORIENTATION;
exports.CAST_PER_CORNER_ORIENTATION = CAST_PER_CORNER_ORIENTATION;
